create table disks (
  id BIGSERIAL NOT NULL PRIMARY KEY,
	width INT,
	ports INT,
	brand VARCHAR(50)
);
insert into disks (width, ports, brand) values (8, 5, 'Hyundai');
insert into disks (width, ports, brand) values (12, 5, 'Infiniti');
insert into disks (width, ports, brand) values (13, 4, 'Toyota');
insert into disks (width, ports, brand) values (11, 4, 'Ford');
insert into disks (width, ports, brand) values (11, 6, 'Volkswagen');
insert into disks (width, ports, brand) values (8, 5, 'Infiniti');
insert into disks (width, ports, brand) values (11, 6, 'Dodge');
insert into disks (width, ports, brand) values (11, 6, 'Ford');
insert into disks (width, ports, brand) values (7, 5, 'Nissan');
insert into disks (width, ports, brand) values (6, 5, 'Ford');
insert into disks (width, ports, brand) values (10, 4, 'Ford');
insert into disks (width, ports, brand) values (6, 5, 'Jeep');
insert into disks (width, ports, brand) values (14, 4, 'Land Rover');
insert into disks (width, ports, brand) values (11, 5, 'Kia');
insert into disks (width, ports, brand) values (7, 6, 'GMC');
insert into disks (width, ports, brand) values (14, 6, 'Cadillac');
insert into disks (width, ports, brand) values (12, 6, 'Ford');
insert into disks (width, ports, brand) values (15, 6, 'GMC');
insert into disks (width, ports, brand) values (15, 6, 'Pontiac');
insert into disks (width, ports, brand) values (7, 6, 'Saab');
insert into disks (width, ports, brand) values (9, 4, 'Land Rover');
insert into disks (width, ports, brand) values (15, 6, 'Mazda');
insert into disks (width, ports, brand) values (6, 5, 'GMC');
insert into disks (width, ports, brand) values (11, 6, 'Dodge');
insert into disks (width, ports, brand) values (15, 4, 'Mazda');
insert into disks (width, ports, brand) values (9, 4, 'Buick');
insert into disks (width, ports, brand) values (9, 4, 'Ford');
insert into disks (width, ports, brand) values (12, 6, 'GMC');
insert into disks (width, ports, brand) values (15, 5, 'Lincoln');
insert into disks (width, ports, brand) values (11, 5, 'Ford');
insert into disks (width, ports, brand) values (10, 5, 'MINI');
insert into disks (width, ports, brand) values (12, 5, 'Saab');
insert into disks (width, ports, brand) values (6, 5, 'Mercedes-Benz');
insert into disks (width, ports, brand) values (12, 4, 'Volvo');
insert into disks (width, ports, brand) values (13, 6, 'Buick');
insert into disks (width, ports, brand) values (8, 6, 'Land Rover');
insert into disks (width, ports, brand) values (13, 4, 'Cadillac');
insert into disks (width, ports, brand) values (8, 4, 'Aston Martin');
insert into disks (width, ports, brand) values (6, 6, 'Mercury');
insert into disks (width, ports, brand) values (12, 5, 'GMC');
insert into disks (width, ports, brand) values (8, 6, 'Aston Martin');
insert into disks (width, ports, brand) values (7, 5, 'Jaguar');
insert into disks (width, ports, brand) values (12, 4, 'Chevrolet');
insert into disks (width, ports, brand) values (13, 4, 'Lexus');
insert into disks (width, ports, brand) values (10, 6, 'Ford');
insert into disks (width, ports, brand) values (9, 4, 'Saturn');
insert into disks (width, ports, brand) values (10, 5, 'Mazda');
insert into disks (width, ports, brand) values (14, 5, 'Isuzu');
insert into disks (width, ports, brand) values (10, 4, 'Dodge');
insert into disks (width, ports, brand) values (11, 6, 'Toyota');
insert into disks (width, ports, brand) values (14, 6, 'Ford');
insert into disks (width, ports, brand) values (10, 5, 'Mazda');
insert into disks (width, ports, brand) values (7, 6, 'Land Rover');
insert into disks (width, ports, brand) values (11, 5, 'Cadillac');
insert into disks (width, ports, brand) values (11, 4, 'Pontiac');
insert into disks (width, ports, brand) values (9, 5, 'Mercedes-Benz');
insert into disks (width, ports, brand) values (8, 6, 'Volvo');
insert into disks (width, ports, brand) values (8, 4, 'Chevrolet');
insert into disks (width, ports, brand) values (10, 5, 'Saab');
insert into disks (width, ports, brand) values (9, 5, 'Volkswagen');
insert into disks (width, ports, brand) values (12, 4, 'Mercedes-Benz');
insert into disks (width, ports, brand) values (8, 4, 'Honda');
insert into disks (width, ports, brand) values (15, 6, 'Ford');
insert into disks (width, ports, brand) values (6, 5, 'Infiniti');
insert into disks (width, ports, brand) values (6, 6, 'Mazda');
insert into disks (width, ports, brand) values (9, 5, 'Acura');
insert into disks (width, ports, brand) values (9, 4, 'Toyota');
insert into disks (width, ports, brand) values (14, 4, 'Toyota');
insert into disks (width, ports, brand) values (14, 5, 'Mercury');
insert into disks (width, ports, brand) values (15, 5, 'Chevrolet');
insert into disks (width, ports, brand) values (12, 6, 'Oldsmobile');
insert into disks (width, ports, brand) values (8, 5, 'Aston Martin');
insert into disks (width, ports, brand) values (10, 5, 'Mazda');
insert into disks (width, ports, brand) values (7, 5, 'Chevrolet');
insert into disks (width, ports, brand) values (7, 6, 'Honda');
insert into disks (width, ports, brand) values (14, 4, 'Volvo');
insert into disks (width, ports, brand) values (14, 5, 'Pontiac');
insert into disks (width, ports, brand) values (6, 6, 'Audi');
insert into disks (width, ports, brand) values (15, 4, 'Chevrolet');
insert into disks (width, ports, brand) values (9, 4, 'Mazda');
insert into disks (width, ports, brand) values (10, 4, 'Dodge');
insert into disks (width, ports, brand) values (11, 5, 'Porsche');
insert into disks (width, ports, brand) values (7, 6, 'Chevrolet');
insert into disks (width, ports, brand) values (10, 5, 'Bentley');
insert into disks (width, ports, brand) values (8, 6, 'Chevrolet');
insert into disks (width, ports, brand) values (11, 6, 'Audi');
insert into disks (width, ports, brand) values (15, 5, 'Mitsubishi');
insert into disks (width, ports, brand) values (6, 5, 'Chevrolet');
insert into disks (width, ports, brand) values (7, 5, 'Mitsubishi');
insert into disks (width, ports, brand) values (11, 6, 'Ford');
insert into disks (width, ports, brand) values (7, 6, 'Mercedes-Benz');
insert into disks (width, ports, brand) values (10, 6, 'Chevrolet');
insert into disks (width, ports, brand) values (14, 4, 'Ford');
insert into disks (width, ports, brand) values (11, 5, 'Nissan');
insert into disks (width, ports, brand) values (11, 4, 'Lexus');
insert into disks (width, ports, brand) values (7, 6, 'Ferrari');
insert into disks (width, ports, brand) values (15, 4, 'Chevrolet');
insert into disks (width, ports, brand) values (13, 4, 'Maybach');
insert into disks (width, ports, brand) values (6, 5, 'GMC');
insert into disks (width, ports, brand) values (12, 4, 'Mazda');
