create table tyres (
  id BIGSERIAL NOT NULL PRIMARY KEY,
	width INT NOT NULL,
	height INT NOT NULL,
	radius INT NOT NULL,
	season VARCHAR(6) NOT NULL,
	brand VARCHAR(50) NOT NULL
);
insert into tyres (width, height, radius, season, brand) values (158, 46, 23, 'winter', 'Toyota');
insert into tyres (width, height, radius, season, brand) values (146, 37, 22, 'winter', 'Oldsmobile');
insert into tyres (width, height, radius, season, brand) values (124, 33, 25, 'winter', 'Ford');
insert into tyres (width, height, radius, season, brand) values (134, 43, 17, 'summer', 'Lotus');
insert into tyres (width, height, radius, season, brand) values (116, 42, 23, 'summer', 'Acura');
insert into tyres (width, height, radius, season, brand) values (151, 51, 15, 'winter', 'Dodge');
insert into tyres (width, height, radius, season, brand) values (260, 65, 17, 'summer', 'Volkswagen');
insert into tyres (width, height, radius, season, brand) values (267, 60, 19, 'summer', 'Lamborghini');
insert into tyres (width, height, radius, season, brand) values (134, 41, 23, 'winter', 'Ford');
insert into tyres (width, height, radius, season, brand) values (160, 38, 14, 'summer', 'Kia');
insert into tyres (width, height, radius, season, brand) values (182, 36, 15, 'winter', 'Lotus');
insert into tyres (width, height, radius, season, brand) values (134, 56, 19, 'winter', 'Audi');
insert into tyres (width, height, radius, season, brand) values (213, 64, 19, 'summer', 'Volvo');
insert into tyres (width, height, radius, season, brand) values (275, 66, 22, 'summer', 'Buick');
insert into tyres (width, height, radius, season, brand) values (281, 49, 25, 'summer', 'Ford');
insert into tyres (width, height, radius, season, brand) values (277, 52, 23, 'winter', 'Nissan');
insert into tyres (width, height, radius, season, brand) values (264, 38, 25, 'summer', 'Oldsmobile');
insert into tyres (width, height, radius, season, brand) values (125, 42, 14, 'summer', 'Lamborghini');
insert into tyres (width, height, radius, season, brand) values (204, 61, 22, 'summer', 'Pontiac');
insert into tyres (width, height, radius, season, brand) values (232, 51, 16, 'winter', 'Toyota');
insert into tyres (width, height, radius, season, brand) values (277, 66, 21, 'summer', 'Ford');
insert into tyres (width, height, radius, season, brand) values (149, 34, 19, 'summer', 'Chevrolet');
insert into tyres (width, height, radius, season, brand) values (116, 54, 25, 'summer', 'Mercury');
insert into tyres (width, height, radius, season, brand) values (137, 30, 20, 'summer', 'GMC');
insert into tyres (width, height, radius, season, brand) values (167, 30, 14, 'winter', 'Mitsubishi');
insert into tyres (width, height, radius, season, brand) values (244, 70, 23, 'summer', 'Chevrolet');
insert into tyres (width, height, radius, season, brand) values (261, 46, 20, 'winter', 'Volvo');
insert into tyres (width, height, radius, season, brand) values (162, 38, 14, 'summer', 'Nissan');
insert into tyres (width, height, radius, season, brand) values (120, 32, 22, 'winter', 'Volkswagen');
insert into tyres (width, height, radius, season, brand) values (209, 46, 13, 'winter', 'BMW');
insert into tyres (width, height, radius, season, brand) values (288, 45, 19, 'winter', 'Jeep');
insert into tyres (width, height, radius, season, brand) values (239, 67, 20, 'winter', 'Volkswagen');
insert into tyres (width, height, radius, season, brand) values (267, 33, 19, 'summer', 'Mercedes-Benz');
insert into tyres (width, height, radius, season, brand) values (292, 61, 17, 'winter', 'Mercury');
insert into tyres (width, height, radius, season, brand) values (151, 42, 13, 'winter', 'Cadillac');
insert into tyres (width, height, radius, season, brand) values (152, 65, 18, 'winter', 'Honda');
insert into tyres (width, height, radius, season, brand) values (274, 53, 24, 'winter', 'GMC');
insert into tyres (width, height, radius, season, brand) values (194, 52, 14, 'winter', 'Oldsmobile');
insert into tyres (width, height, radius, season, brand) values (226, 44, 22, 'winter', 'Mitsubishi');
insert into tyres (width, height, radius, season, brand) values (182, 41, 21, 'winter', 'BMW');
insert into tyres (width, height, radius, season, brand) values (125, 69, 17, 'winter', 'Porsche');
insert into tyres (width, height, radius, season, brand) values (240, 67, 16, 'winter', 'Chevrolet');
insert into tyres (width, height, radius, season, brand) values (275, 52, 14, 'winter', 'Toyota');
insert into tyres (width, height, radius, season, brand) values (203, 69, 17, 'winter', 'Toyota');
insert into tyres (width, height, radius, season, brand) values (197, 70, 22, 'summer', 'Nissan');
insert into tyres (width, height, radius, season, brand) values (234, 65, 19, 'summer', 'Dodge');
insert into tyres (width, height, radius, season, brand) values (269, 48, 17, 'winter', 'Toyota');
insert into tyres (width, height, radius, season, brand) values (176, 60, 20, 'winter', 'Mercedes-Benz');
insert into tyres (width, height, radius, season, brand) values (286, 36, 22, 'winter', 'Buick');
insert into tyres (width, height, radius, season, brand) values (194, 31, 23, 'winter', 'Mazda');
insert into tyres (width, height, radius, season, brand) values (295, 68, 13, 'winter', 'BMW');
insert into tyres (width, height, radius, season, brand) values (269, 50, 23, 'summer', 'Toyota');
insert into tyres (width, height, radius, season, brand) values (158, 59, 17, 'summer', 'Toyota');
insert into tyres (width, height, radius, season, brand) values (156, 64, 18, 'winter', 'Ford');
insert into tyres (width, height, radius, season, brand) values (243, 58, 19, 'summer', 'Mitsubishi');
insert into tyres (width, height, radius, season, brand) values (213, 35, 25, 'winter', 'Land Rover');
insert into tyres (width, height, radius, season, brand) values (157, 60, 15, 'winter', 'Cadillac');
insert into tyres (width, height, radius, season, brand) values (206, 38, 15, 'winter', 'Pontiac');
insert into tyres (width, height, radius, season, brand) values (271, 61, 13, 'summer', 'Dodge');
insert into tyres (width, height, radius, season, brand) values (148, 55, 15, 'winter', 'Honda');
insert into tyres (width, height, radius, season, brand) values (230, 37, 19, 'summer', 'Mazda');
insert into tyres (width, height, radius, season, brand) values (285, 62, 17, 'winter', 'Pontiac');
insert into tyres (width, height, radius, season, brand) values (173, 30, 21, 'summer', 'Ford');
insert into tyres (width, height, radius, season, brand) values (194, 45, 23, 'winter', 'Infiniti');
insert into tyres (width, height, radius, season, brand) values (244, 46, 21, 'winter', 'GMC');
insert into tyres (width, height, radius, season, brand) values (267, 43, 14, 'winter', 'Buick');
insert into tyres (width, height, radius, season, brand) values (215, 32, 14, 'winter', 'Volkswagen');
insert into tyres (width, height, radius, season, brand) values (248, 47, 17, 'summer', 'Scion');
insert into tyres (width, height, radius, season, brand) values (272, 49, 22, 'summer', 'Ford');
insert into tyres (width, height, radius, season, brand) values (144, 30, 16, 'winter', 'Mercury');
insert into tyres (width, height, radius, season, brand) values (193, 68, 17, 'summer', 'Toyota');
insert into tyres (width, height, radius, season, brand) values (200, 33, 19, 'winter', 'Infiniti');
insert into tyres (width, height, radius, season, brand) values (218, 35, 17, 'winter', 'Dodge');
insert into tyres (width, height, radius, season, brand) values (263, 52, 14, 'winter', 'Infiniti');
insert into tyres (width, height, radius, season, brand) values (259, 35, 24, 'summer', 'Honda');
insert into tyres (width, height, radius, season, brand) values (198, 32, 14, 'winter', 'BMW');
insert into tyres (width, height, radius, season, brand) values (178, 42, 24, 'winter', 'Plymouth');
insert into tyres (width, height, radius, season, brand) values (251, 32, 24, 'summer', 'Infiniti');
insert into tyres (width, height, radius, season, brand) values (160, 58, 17, 'winter', 'Acura');
insert into tyres (width, height, radius, season, brand) values (295, 37, 13, 'winter', 'Infiniti');
insert into tyres (width, height, radius, season, brand) values (142, 33, 16, 'winter', 'Mercury');
insert into tyres (width, height, radius, season, brand) values (209, 38, 23, 'summer', 'Saab');
insert into tyres (width, height, radius, season, brand) values (300, 43, 21, 'winter', 'Mazda');
insert into tyres (width, height, radius, season, brand) values (187, 54, 14, 'winter', 'Geo');
insert into tyres (width, height, radius, season, brand) values (271, 53, 20, 'summer', 'Ford');
insert into tyres (width, height, radius, season, brand) values (138, 32, 14, 'winter', 'Hyundai');
insert into tyres (width, height, radius, season, brand) values (221, 30, 14, 'winter', 'Dodge');
insert into tyres (width, height, radius, season, brand) values (177, 57, 23, 'winter', 'Bentley');
insert into tyres (width, height, radius, season, brand) values (169, 57, 24, 'summer', 'Mazda');
insert into tyres (width, height, radius, season, brand) values (164, 68, 20, 'summer', 'Maserati');
insert into tyres (width, height, radius, season, brand) values (216, 57, 24, 'summer', 'Land Rover');
insert into tyres (width, height, radius, season, brand) values (134, 56, 13, 'winter', 'GMC');
insert into tyres (width, height, radius, season, brand) values (140, 64, 19, 'winter', 'Isuzu');
insert into tyres (width, height, radius, season, brand) values (167, 54, 24, 'summer', 'GMC');
insert into tyres (width, height, radius, season, brand) values (245, 33, 13, 'summer', 'Volvo');
insert into tyres (width, height, radius, season, brand) values (292, 50, 19, 'summer', 'Dodge');
insert into tyres (width, height, radius, season, brand) values (248, 34, 14, 'winter', 'Dodge');
insert into tyres (width, height, radius, season, brand) values (255, 58, 22, 'summer', 'Volkswagen');
insert into tyres (width, height, radius, season, brand) values (155, 36, 20, 'summer', 'Ford');
insert into tyres (width, height, radius, season, brand) values (242, 69, 25, 'winter', 'BMW');
